### ISSUE TITLE
Compiling with SFML throws errors on Travis

### ISSUE THREAD

**Issue by FlyingGraysons** [FidoProject/Fido#23]
In this travis build, the SFML option is enabled, but the build fails.  
https://travis-ci.org/FidoProject/Fido/jobs/117522028#L192  
Maybe its something on the Travis side, maybe not. At least fix the .travis.yml file.

**Comment by truell20** [comment]
This was fixed in @FlyingGraysons's pull request. He fixed the way he installed sfml.
