### ISSUE TITLE
No "Fido" implementation according to @joshuagruenstein and my research

### ISSUE THREAD

**Issue by truell20** [FidoProject/Fido#25]

**Comment by joshuagruenstein** [comment]
this is super important
@truell20

**Comment by truell20** [comment]
@joshuagruenstein Its just a Robot object with a WireFitQLearn learning model, so its kind of already implemented

**Comment by truell20** [comment]
@joshuagruenstein It would require fixing NN architecture, learning rate, interpolator, etc. for all tasks.

**Comment by truell20** [comment]
@joshuagruenstein Nevermind. With the changes that I am implementing (more trainers, history sampling) a separate Fido implementation will make sense
