### ISSUE TITLE
API dealing with TensorFLow's models ?

### ISSUE THREAD

**Issue by dorje** [FidoProject/Fido#48]
Hi guys,
I am trying to apply TensorFlow trained models to embedded systems, say, Raspberry Pi, or even much less power boards with no OS.

So, have you ever thought to develop something can use models of TensofFlow on very tiny devices?

Cheers,
Dorje

**Comment by truell20** [comment]
We don't currently plan on integrating with TensorFlow models. Having a repository of trained models is something to consider in the future.
