### ISSUE TITLE
Poor error handling

### ISSUE THREAD

**Issue by joshuagruenstein** [FidoProject/Fido#49]
Errors are handled by throwing 1 and printing the message with std::cout.  This should instead use std::runtime_exception.

**Comment by truell20** [comment]
std::runtime_exception should not be used since we are moving away from the standard library since it isnt really supported on microcontrollers.

**Comment by truell20** [comment]
We could use a preprocessor directive to check for the existence of exceptions and throw them if they exist?

**Comment by truell20** [comment]
@joshuagruenstein @FlyingGraysons Ben suggested using `assert` instead of `std::runtime_exception` or `throw`. It is C code, so will be available on microcontrollers. Right?

**Comment by truell20** [comment]
Fixed in 65d4f8c63ad57d9bd68a13962fb5a341580f65d9
