### ISSUE TITLE
Doxygen Documentation

### ISSUE THREAD

**Issue by truell20** [FidoProject/Fido#5]
We need to switch to the doxygen comment style, so that the generated html documentation will include our descriptions.

**Comment by truell20** [comment]
@joshuagruenstein description of doxygen documentation https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html

**Comment by truell20** [comment]
Example:
http://fidoproject.github.io/docs/html/classnet_1_1_backpropagation.html
https://github.com/FidoProject/Fido/blob/master/Software/Backpropagation.h

**Comment by truell20** [comment]
@FlyingGraysons, @joshuagruenstein agreed to do this.

**Comment by FlyingGraysons** [comment]
@joshuagruenstein @truell20 
http://testgen.cvs.sourceforge.net/viewvc/testgen/testgen/
http://stackoverflow.com/a/32841496

Both are scripts (the second one is kinda broken) which claim to add doxygen. Probably will require some code changes, but looks easier than writing a parser from scratch

**Comment by truell20** [comment]
@joshuagruenstein WireFitQLearn and QLearn are left

**Comment by truell20** [comment]
Also the simulator, robby, and emitter
