### ISSUE TITLE
Compilation of project fails on Mac OS & Ubuntu 16.04

### ISSUE THREAD

**Issue by astroesteban** [FidoProject/Fido#69]
When I attempt to compile the project using `sudo make install`, I receive a fatal error: 'SFML/Graphics.hpp' file not found

This error happened on both my Mac OS Version 10.13.3 and Ubuntu 16.04. 

![screen shot 2018-02-04 at 6 59 37 pm](https://user-images.githubusercontent.com/12473592/35784537-281fde58-09de-11e8-861d-2aeed7b85545.png)

**Comment by truell20** [comment]
Thanks for opening this issue!

We haven't updated the install instructions, but you should have the SFML graphics library installed. Our robotic simulator relies on it.

On ubuntu you can install SFML with:

`sudo apt-get install libsfml-dev`

For more info, visit the [SFML site](https://www.sfml-dev.org/tutorials/2.0/start-linux.php).

**Comment by astroesteban** [comment]
Great! Thanks for the help!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
